services:
  secure-app:
    build: .
    image: rsa-demo-java:local
    container_name: rsa-demo-secure-app
    environment:
      APP_MODE: secure
      SERVICE_NAME: secure-app
      LOG_FILE: /logs/events.jsonl
      RSA_KEY_BITS: "3072"
      MAX_CRYPTO_OPS_PER_MIN: "120"
      HTTP_THREADS: "8"
    ports:
      - "8080:8080"
    volumes:
      - demo-logs:/logs

  dashboard:
    image: rsa-demo-java:local
    depends_on:
      - secure-app
    environment:
      SERVICE_NAME: dashboard
      LOG_FILE: /logs/events.jsonl
      DASHBOARD_PORT: "8090"
      DASHBOARD_INITIAL_EVENTS: "5000"
    ports:
      - "8090:8090"
    volumes:
      - demo-logs:/logs
    command: ["java", "-cp", "/app/out", "demo.DashboardApp"]

  normal-demo:
    image: rsa-demo-java:local
    profiles: ["demo"]
    depends_on:
      - secure-app
    environment:
      SERVICE_NAME: normal-demo
      LOG_FILE: /logs/events.jsonl
      TARGET_URL: http://secure-app:8080
    volumes:
      - demo-logs:/logs
    command: ["java", "-cp", "/app/out", "demo.AttackClient", "normal-secure"]

volumes:
  demo-logs:
